name: Build and Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install FVM via curl
        run: curl -fsSL https://fvm.app/install.sh | bash

      - name: Install Flutter version with FVM
        run: fvm install

      - name: Use Flutter version with FVM
        run: fvm use

      - name: Install dependencies
        run: fvm flutter pub get

      - name: Enable Flutter Web
        run: fvm flutter create .

      - name: Generate Freezed files
        run: fvm flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Flutter Web app
        run: fvm flutter build web --output=gh-pages --base-href=/flutter_notes/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: gh-pages
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deployment completed
        run: echo "Deployment to GitHub Pages completed successfully."
